# env
spring:
  profiles:
    include: env, actuator, keycloak

# DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${my.mysqluri_local}
    username: ${my.mysqlUsername}
    password: ${my.mysqlPassword}

# data.sql
  sql:
    init:
      mode: never
    defer-datasource-initialization: true
    open-in-view: false

  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          show_sql: true
          format_sql: true

# Redis
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
---
spring:
  config:
    activate:
      on-profile: prod
  # DB
  datasource:
    url: ${my.mysqluri_docker}

  # data.sql
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false

  # spring security
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    # logging
    root: error

  # Redis
  data:
    redis:
      host: db-redis
      port: 6379