my:
  mysqlUsername: apiuser
  mysqlPassword: api1234
  mysqluri_local: jdbc:mysql://localhost:3306/zanbanzero?useSSL=false&allowPublicKeyRetrieval=true
  mysqluri_docker: jdbc:mysql://db-mysql:3306/zanbanzero?useSSL=false