INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user1', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user2', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user3', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user4', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user5', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user6', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user7', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user8', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user9', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user10', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user11', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user12', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user13', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user14', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user15', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user16', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user17', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user18', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('manager', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_MANAGER');

INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (1, 1, 0, 0, 0, 0, 1);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (2, 0, 1, 0, 0, 0, 1);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (3, 0, 0, 1, 0, 0, 1);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (4, 0, 0, 0, 1, 0, 1);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (5, 0, 0, 0, 0, 1, 1);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (6, 1, 0, 1, 0, 1, 2);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (7, 1, 0, 1, 0, 1, 2);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (8, 1, 0, 1, 0, 1, 2);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (9, 1, 0, 1, 0, 1, 2);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (10, 0, 1, 1, 1, 0, 2);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (11, 0, 1, 1, 1, 0, 3);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (12, 0, 1, 1, 1, 0, 3);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (13, 1, 1, 1, 0, 0, 3);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (14, 1, 1, 1, 0, 0, 3);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (15, 0, 0, 1, 1, 1, 3);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (16, 0, 0, 1, 1, 1, 4);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (17, 1, 0, 1, 1, 1, 4);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (18, 1, 1, 1, 0, 1, 4);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (19, 0, 0, 1, 0, 0, 4);

INSERT INTO zanbanzero.menu(cost, name, sold, use_planner) VALUES (5000, "백반 정식", true, true);
INSERT INTO zanbanzero.menu(cost, name, sold, use_planner) VALUES (6000, "촌돼지 김치찌개", true, false);
INSERT INTO zanbanzero.menu(cost, name, sold, use_planner) VALUES (8000, "가마치통닭", true, false);
INSERT INTO zanbanzero.menu(cost, name, sold, use_planner) VALUES (6000, "부대찌개", true, false);

INSERT INTO zanbanzero.planner(menu_id, date, menus) VALUES (1, '2023-03-02', '닭발 콩나무물무침 계란말이');
INSERT INTO zanbanzero.planner(menu_id, date, menus) VALUES (1, '2023-03-03', '닭발 잭과콩나무');
INSERT INTO zanbanzero.planner(menu_id, date, menus) VALUES (1, '2023-04-02', '피자');
INSERT INTO zanbanzero.planner(menu_id, date, menus) VALUES (1, '2023-04-03', '치킨너겟 케찹');
INSERT INTO zanbanzero.planner(menu_id, date, menus) VALUES (1, '2023-04-04', '닭가슴살 훈제');
INSERT INTO zanbanzero.planner(menu_id, date, menus) VALUES (1, '2023-04-05', '건강 밀키트');
INSERT INTO zanbanzero.planner(menu_id, date, menus) VALUES (1, '2023-04-06', '콩나물죽 김치볶음');
INSERT INTO zanbanzero.planner(menu_id, date, menus) VALUES (1, '2023-04-07', '지옥의 삼겹살');
INSERT INTO zanbanzero.planner(menu_id, date, menus) VALUES (1, '2023-04-22', '강낭콩볶음 훈제로스트치킨');

INSERT INTO zanbanzero.calculate(date) VALUES ('2023-04-03');
INSERT INTO zanbanzero.calculate(date) VALUES ('2023-04-04');
INSERT INTO zanbanzero.calculate(date) VALUES ('2023-04-05');
INSERT INTO zanbanzero.calculate(date) VALUES ('2023-04-06');
INSERT INTO zanbanzero.calculate(date) VALUES ('2023-04-07');
INSERT INTO zanbanzero.calculate(date) VALUES ('2023-04-10');
INSERT INTO zanbanzero.calculate(date) VALUES ('2023-04-11');
INSERT INTO zanbanzero.calculate(date) VALUES ('2023-04-12');
INSERT INTO zanbanzero.calculate(date) VALUES ('2023-04-13');
INSERT INTO zanbanzero.calculate(date) VALUES ('2023-04-14');
INSERT INTO zanbanzero.calculate(date) VALUES ('2023-04-17');
INSERT INTO zanbanzero.calculate(date) VALUES ('2023-04-18');
INSERT INTO zanbanzero.calculate(date) VALUES ('2023-04-29');

INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (1, 1, 13, 13 * 5000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (1, 2, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (1, 3, 13, 13 * 8000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (1, 4, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (2, 1, 13, 13 * 5000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (2, 2, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (2, 3, 13, 13 * 8000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (2, 4, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (3, 1, 13, 13 * 5000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (3, 2, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (3, 3, 13, 13 * 8000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (3, 4, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (4, 1, 13, 13 * 5000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (4, 2, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (4, 3, 13, 13 * 8000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (4, 4, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (5, 1, 13, 13 * 5000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (5, 2, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (5, 3, 13, 13 * 8000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (5, 4, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (6, 1, 13, 13 * 5000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (6, 2, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (6, 3, 13, 13 * 8000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (6, 4, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (7, 1, 13, 13 * 5000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (7, 2, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (7, 3, 13, 13 * 8000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (7, 4, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (8, 1, 13, 13 * 5000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (8, 2, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (8, 3, 13, 13 * 8000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (8, 4, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (9, 1, 13, 13 * 5000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (9, 2, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (9, 3, 13, 13 * 8000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (9, 4, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (10, 1, 13, 13 * 5000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (10, 2, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (10, 3, 13, 13 * 8000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (10, 4, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (11, 1, 13, 13 * 5000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (11, 2, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (11, 3, 13, 13 * 8000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (11, 4, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (12, 1, 13, 13 * 5000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (12, 2, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (12, 3, 13, 13 * 8000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (12, 4, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (13, 1, 13, 13 * 5000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (13, 2, 13, 13 * 6000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (13, 3, 13, 13 * 8000);
INSERT INTO zanbanzero.calculate_menu(calculate_id, menu_id, count, sales) VALUES (13, 4, 13, 13 * 6000);