INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user1', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user2', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user3', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user4', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user5', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user6', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user7', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user8', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user9', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user10', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user11', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user12', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user13', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user14', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user15', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user16', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user17', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');
INSERT INTO zanbanzero.user(username, password, roles) VALUES ('user18', '$2a$10$rb7fhQHdtxNf7RgTJVlERePH99.BqB6/i5LE61leYMh0vGOQoGbIC', 'ROLE_USER');

INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (1, 1, 0, 0, 0, 0, 1);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (2, 0, 1, 0, 0, 0, 1);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (3, 0, 0, 1, 0, 0, 1);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (4, 0, 0, 0, 1, 0, 1);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (5, 0, 0, 0, 0, 1, 1);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (6, 1, 0, 1, 0, 1, 2);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (7, 1, 0, 1, 0, 1, 2);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (8, 1, 0, 1, 0, 1, 2);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (9, 1, 0, 1, 0, 1, 2);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (10, 0, 1, 1, 1, 0, 2);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (11, 0, 1, 1, 1, 0, 3);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (12, 0, 1, 1, 1, 0, 3);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (13, 1, 1, 1, 0, 0, 3);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (14, 1, 1, 1, 0, 0, 3);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (15, 0, 0, 1, 1, 1, 3);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (16, 0, 0, 1, 1, 1, 4);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (17, 1, 0, 1, 1, 1, 4);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (18, 1, 1, 1, 0, 1, 4);
INSERT INTO zanbanzero.user_policy(user_id, monday, tuesday, wednesday, thursday, friday, default_menu) VALUES (19, 0, 0, 1, 0, 0, 4);


INSERT INTO zanbanzero.planner(date, menus, off) VALUES ('2023-03-02', '닭발 콩나무물무침 계란말이', false);
INSERT INTO zanbanzero.planner(date, menus, off) VALUES ('2023-03-03', '닭발 잭과콩나무', false);
INSERT INTO zanbanzero.planner(date, menus, off) VALUES ('2023-04-02', '피자', false);
INSERT INTO zanbanzero.planner(date, menus, off) VALUES ('2023-04-03', '치킨너겟 케찹', false);
INSERT INTO zanbanzero.planner(date, menus, off) VALUES ('2023-04-04', '닭가슴살 훈제', false);
INSERT INTO zanbanzero.planner(date, menus, off) VALUES ('2023-04-05', '건강 밀키트', false);
INSERT INTO zanbanzero.planner(date, menus, off) VALUES ('2023-04-06', '콩나물죽 김치볶음', false);
INSERT INTO zanbanzero.planner(date, menus, off) VALUES ('2023-04-07', '지옥의 삼겹살', false);
INSERT INTO zanbanzero.planner(date, menus, off) VALUES ('2023-04-22', '강낭콩볶음 훈제로스트치킨', false);