version: '3.7'
services:
  db-mysql:
    image: mysql:8.0.0
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: zanbanzero
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: Asia/Seoul
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db-mysql

  db-redis:
    image: redis:latest
    ports:
      - "6379:6379"

  os-ubuntu:
    image: ubuntu:latest
    ports:
      - "80:80"
    tty: true

