# Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, prometheus
      base-path: ENC(7Br3hhVq66/sAE7e8i8KARuAE36elNWc5NBqKIXGaEs=)

  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true

my:
  actuator:
    path: ENC(3aT/vVhONgwb9fUNyYcql3dB4otCYZzQvCWi4j5GLjE=)
  prometheus:
    path: ENC(cJN1Pem0F1zgoqBxW/lwXAi850Y8mfTv7f/SGlIH160+AkX5Zo7h/Q==)
  server:
    address: ENC(Y8y6usFFNuq1/0VKRVTzPYDaI1xTOPTh)