# env
spring:
  profiles:
    include: db, slack, keycloakAuth, chatgptApi, monitor

  application:
    name: zanbanzero

  task:
    execution:
      pool:
        core-size: 1
        max-size: 1

  # data.sql
  jpa:
    hibernate:
      ddl-auto: create
    properties:
        hibernate:
          show_sql: true
          format_sql: true
  sql:
    init:
      mode: never

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
---
spring:
  config:
    activate:
      on-profile: prod

  # data.sql
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false

    # logging
    root: error