# env
spring:
  profiles:
    include: db, actuator, slack, keycloakAuth, chatgptApi

  application:
    name: zanbanzero

  task:
    execution:
      pool:
        core-size: 1
        max-size: 1

  # data.sql
  jpa:
    hibernate:
      ddl-auto: create
    properties:
        hibernate:
          show_sql: true
          format_sql: true
  sql:
    init:
      mode: never

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, prometheus

  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod

  # data.sql
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false

    # logging
    root: error