# env
spring:
  profiles:
    include: db, actuator, keycloak, slack, rabbitmq

  application:
    name: zanbanzero

  # data.sql
  jpa:
    hibernate:
      ddl-auto: create
    properties:
        hibernate:
          show_sql: true
          format_sql: true
  sql:
    init:
      mode: never

  # Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, prometheus

  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true

  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3_single
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: "http://kjj.kjj.r-e.kr:9411/api/v2/spans"
---
spring:
  config:
    activate:
      on-profile: prod

  # data.sql
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false

  # spring security
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    # logging
    root: error