spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${mysql.uri-dev}
      username: ${mysql.username}
      password: ${mysql.slave.password}
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${mysql.slave.uri}
      username: ${mysql.slave.username}
      password: ${mysql.slave.password}

  # Redis
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    master:
      jdbc-url: ${mysql.uri}

  # Redis
  data:
    redis:
      host: db-redis
      port: 6379