# env
spring:
  profiles:
    include: slack, monitor

# Batch Table
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: ENC(wcMTQBSY8e9Noi4nhYNys8lhE/ZEtY1p9Su5rPEB7d3XcSfvXpFFKCTh7wdG8AUuhs/SsTWjYATOasNmTXMo/jq374Wp8HHo)
    username: ENC(ablWyFhr4StpQS5uR2duxH5hfd4Gllp2)
    password: ENC(BUIhVSzuPftr//0joDiak/zvZ/AbOJDX)
    data:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(7Vcf+03tOggTi0grSNA2c+DD5DgFehwSVBNMuH28OpaEpPJjUzJO5EzAOAUvD9Iudv5/tXtLn3KKeQf8kHyj2g==)
      username: ENC(ablWyFhr4StpQS5uR2duxH5hfd4Gllp2)
      password: ENC(BUIhVSzuPftr//0joDiak/zvZ/AbOJDX)

# spring
  main:
    allow-bean-definition-overriding: true

# batch
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

# jasypt
jasypt:
  encryptor:
    bean: jasypt
---
spring:
  config:
    activate.on-profile: dev
# DB
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/zanbanzero_batch?useSSL=false&allowPublicKeyRetrieval=true
    data:
      jdbc-url: jdbc:mysql://localhost:3306/zanbanzero?useSSL=false&allowPublicKeyRetrieval=true