my:
  batchuri_docker: jdbc:mysql://db-mysql:3306/zanbanzero_batch?useSSL=false
  mysqluri_docker: jdbc:mysql://db-mysql:3306/zanbanzero?useSSL=false
  mysqlUsername: batchuser
  mysqlPassword: batch1234
  batchuri_local: jdbc:mysql://localhost:3306/zanbanzero_batch?useSSL=false&allowPublicKeyRetrieval=true
  mysqluri_local: jdbc:mysql://localhost:3306/zanbanzero?useSSL=false&allowPublicKeyRetrieval=true